- name: Setup EC2 for Next.js App
  hosts: web
  become: true

  vars:
    container_name: nextjs-app

  tasks:

    - name: Update packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Pull latest image
      command: docker pull {{ image_name }}

    - name: Stop existing container
      command: docker stop {{ container_name }}
      ignore_errors: yes

    - name: Remove existing container
      command: docker rm {{ container_name }}
      ignore_errors: yes

    - name: Deploy container
      command: >
        docker run -d
        --name {{ container_name }}
        --restart always
        -p 80:3000
        {{ image_name }}